apiVersion: v1
kind: ConfigMap
metadata:
  name: aeropartners-config
  namespace: aeropartners
data:
  # Base de datos - URL completa para el código (PostgreSQL local)
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/aeropartners"
  
  # Base de datos - Variables individuales
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "aeropartners"
  DB_USER: "postgres"
  
  # Pulsar
  PULSAR_URL: "pulsar://pulsar-service:6650"
  PULSAR_ADMIN_URL: "http://pulsar-service:8080"
  
  # Servicios de Campañas
  PRIMARY_SERVICE_URL: "http://aeropartners-service:8001"
  REPLICA_SERVICE_URL: "http://aeropartners-service:8002"
  
  # Configuración de servicios
  SERVICE_NAME: "aeropartners"
  SUBSCRIPTION_TYPE: "failover"
  SUBSCRIPTION_NAME: "campaigns-failover"
  DLQ_TOPIC: "campaigns.DLQ"
  MAX_REDELIVER_COUNT: "3"
  ACK_TIMEOUT_MILLIS: "30000"
  NEGATIVE_ACK_REDELIVERY_DELAY_MILLIS: "5000"
  
  # Health checks
  HEALTH_CHECK_INTERVAL: "2"
  HEALTH_CHECK_TIMEOUT: "5"
  MAX_CONSECUTIVE_FAILURES: "3"
  
  # Event Collector
  USE_REDIS: "false"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Servicios de Datos
  SERVICE_VERSION_V1: "v1"
  SERVICE_VERSION_V2: "v2"
  SERVICE_PORT: "8000"
  
  # CORS
  CORS_ORIGINS: "*"
  
  # Logging
  LOG_LEVEL: "INFO"